embedding_size: 64
reg_weight: [1e-03, 1e-04, 1e-05]


# single lfm2k
# vision_feature_file: ['vit_cls.npy', 'vit_avg.npy', 'all-MiniLM-L6-v2.npy', 'all-mpnet-base-v2.npy', 'whisper.npy', 'vggish.npy', 'vgg.npy', 'resnet152.npy']

# single dbbook
# vision_feature_file: ['vit_cls.npy', 'vit_avg.npy', 'vgg.npy', 'resnet152.npy', 'all-MiniLM-L6-v2.npy', 'all-mpnet-base-v2.npy']

# single ml1m
# vision_feature_file: ['vit_cls.npy', 'vit_avg.npy', 'all-MiniLM-L6-v2.npy', 'all-mpnet-base-v2.npy', 'whisper.npy', 'vggish.npy', 'vgg.npy', 'resnet152.npy', 'i3d.npy', 'r2p1d.npy']

# double lfm2k
# vision_feature_file: ['vit_avg.npy', 'whisper.npy', 'all-MiniLM-L6-v2.npy']
# text_feature_file: ['vit_avg.npy', 'whisper.npy', 'all-MiniLM-L6-v2.npy']

# double dbbook
vision_feature_file: ['vit_cls.npy']
text_feature_file: ['all-mpnet-base-v2.npy']

# double ml1m
# vision_feature_file: ['vit_avg.npy', 'whisper.npy', 'all-MiniLM-L6-v2.npy', 'i3d.npy']
# text_feature_file: ['vit_avg.npy', 'whisper.npy', 'all-MiniLM-L6-v2.npy', 'i3d.npy']


hyper_parameters: ["reg_weight", "vision_feature_file", "text_feature_file"]