recdim: 64
layer_num: [1,2,3]
ssl_task: 'FAC'
ssl_alpha: [0.01, 0.1]
ssl_temp: [0.1, 0.5]
dropout_rate: 0.3
mm_fusion_mode: 'concat'
temp: 0.2
init: 'xavier'
adj_type: 'pre'

# single lfm2k
# vision_feature_file: ['vit_cls.npy', 'vit_avg.npy', 'all-MiniLM-L6-v2.npy', 'all-mpnet-base-v2.npy', 'whisper.npy', 'vggish.npy', 'vgg.npy', 'resnet152.npy']

# single dbbook
# vision_feature_file: ['vit_cls.npy', 'vit_avg.npy', 'vgg.npy', 'resnet152.npy', 'all-MiniLM-L6-v2.npy', 'all-mpnet-base-v2.npy']

# single ml1m
# vision_feature_file: ['vit_cls.npy', 'vit_avg.npy', 'all-MiniLM-L6-v2.npy', 'all-mpnet-base-v2.npy', 'whisper.npy', 'vggish.npy', 'vgg.npy', 'resnet152.npy', 'i3d.npy', 'r2p1d.npy']

# double lfm2k
# vision_feature_file: ['vgg.npy', 'vggish.npy', 'all-mpnet-base-v2.npy']
# text_feature_file: ['vgg.npy', 'vggish.npy', 'all-mpnet-base-v2.npy']

# double dbbook
vision_feature_file: ['vgg.npy']
text_feature_file: ['all-mpnet-base-v2.npy']

# double ml1m
# vision_feature_file: ['resnet152.npy', 'whisper.npy', 'all-MiniLM-L6-v2.npy', 'r2p1d.npy']
# text_feature_file: ['resnet152.npy', 'whisper.npy', 'all-MiniLM-L6-v2.npy', 'r2p1d.npy']

hyper_parameters: ["layer_num", "ssl_alpha", "ssl_temp", "vision_feature_file", "text_feature_file"]